In [1]:
import numpy as np

# create a 1D array
a = np.array([1, 2, 3, 4, 5])

# create a 2D array
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# perform basic array operations
c = a + 2
d = b * 3

# print the arrays and the results of the operations
print(a)
print(b)
print(c)
print(d)


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[3 4 5 6 7]
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [2]:
import pandas as pd

# create a DataFrame from a dictionary
data = {'name': ['Alice', 'Bob', 'Charlie', 'David'],
        'age': [25, 32, 18, 47],
        'country': ['USA', 'Canada', 'USA', 'USA']}
df = pd.DataFrame(data)

# print the DataFrame
print(df)

# perform basic data manipulation operations
mean_age = df['age'].mean()
df['age_squared'] = df['age'] ** 2

# print the updated DataFrame and the mean age
print(df)
print(mean_age)


      name  age country
0    Alice   25     USA
1      Bob   32  Canada
2  Charlie   18     USA
3    David   47     USA
      name  age country  age_squared
0    Alice   25     USA          625
1      Bob   32  Canada         1024
2  Charlie   18     USA          324
3    David   47     USA         2209
30.5
